from django.conf.urls import patterns, include, url

from notebook import views

urlpatterns = patterns('',
url(r'^$',views.index, name='index'),
#url(r'^texts/$', views.texts, name='texts'),
#url(r'^texts/(?P<title_text>.+)/$', views.text_detail, name='text_detail'),
url(r'^texts/add/$', views.add_text, name='add_text'),
url(r'^texts/edit/(?P<id_text>.+)/$', views.add_text, name='edit_text'),
url(r'^texts/upload/$', views.upload_text, name='upload_text'),
#url(r'^texts/add/$', views.add_text, name='add_text'),
url(r'^texts/highlight/(?P<txt_id>.+)/$', views.highl, name='highl'),
url(r'^texts/highlight_ajax/$', views.highl_ajax, name='ajax_highl'),
url(r'^texts/show/(?P<id_text>.+)/$', views.show_text, name='show_text'),
url(r'^texts/translate/(?P<id_text>\d+)/all/$', views.translate_terms, {'include_all':True},name='translate_terms_all'),
url(r'^texts/translate/(?P<id_text>.+)/$', views.translate_terms, name='translate_terms'),
url(r'^texts/list/$', views.list_texts, name='list_texts'),
url(r'^texts/search/crossrefs/$', views.search_crossrefs, name='search_crossrefs'),
url(r'^texts/ajax/crossrefs_include/$', views.search_crossrefs_ajax, name='search_crossrefs_ajax'),
url(r'^sec_sources/list/$', views.list_texts,{'secSource':True}, name='list_secSources'),
url(r'^sec_sources/list/review/$', views.list_texts,{'secSource':True,'update':True}, name='list_secSources'),
url(r'^people/list/$', views.list_people, name='list_people'),
url(r'^people/choose/$', views.choose_people, name='choose_people'),
url(r'^people/list/review/$', views.list_people,{'review':True}, name='list_people_review'),
url(r'^people/show/(?P<id_people>[0-9]+)/$', views.show_people, name='show_people'),
url(r'^people/add/$', views.edit_person, name='edit_person'),
url(r'^people/edit/(?P<id_people>[0-9]+)/$', views.edit_person, name='edit_person'),
url(r'^people/show/ajax/$', views.people_net_ajax, name='people_net_ajax'),
url(r'^institutions/list/$', views.list_institutions, name='list_institutions'),
url(r'^institutions/list/review/$', views.list_institutions, {'review':True}, name='list_institutions_review'),
url(r'^institutions/show/(?P<id_institution>.+)/$', views.show_institution, name='list_institution'),
url(r'^institutions/add/$', views.edit_institution, name='edit_institution'),
url(r'^institutions/edit/(?P<id_institution>.+)/$', views.edit_institution, name='edit_institution'),
url(r'^term/add/$', views.add_term, name='add_term'),
url(r'^report/add$', views.add_report, name='add_report'),
url(r'^analysis/class_ajax/$', views.analysis_class_ajax, name='analysis_class_ajax'),
url(r'^analysis/name_ajax/$', views.analysis_name_ajax, name='analysis_name_ajax'),
url(r'^analysis/networks/$', views.analysis_networks_page, name='analysis_networks_page'),
url(r'^analysis/networks_ajax/$', views.analysis_networks_ajax, name='analysis_networks_ajax'),
url(r'^followAjax/$', views.trigger_follow, name='trigger_follow'),
url(r'^concepts/list/$', views.list_concepts, name='list_concepts'),
url(r'^terms/list/$', views.list_terms, name='list_terms'),
url(r'^concepts/show/(?P<id_concept>[0-9]+)/$', views.show_concept, name='show_concept'),
url(r'^terms/show/(?P<id_term>[0-9]+)/$', views.show_term, name='show_term'),


#url(r'^texts/(?P<title_text>.+)/edit/$', views.edit_text, name='edit_text'),
#url(r'^institutions/$', views.institutions, name='institutions'),
#url(r'^institutions/(?P<name_institution>.+)/$', views.institution_detail, name='institution_detail'),
#url(r'^institutions/add/$', views.add_institution, name='add_institution'),
#url(r'^institutions/(?P<name_institution>.+)/edit/$', views.edit_institution, name='edit_institution'),
#url(r'^show/person/(?P<pers_name>.+)/$', views.show_person, name='show_person'),
#url(r'^people/$', views.people, name='people'),
#url(r'^people/(?P<name_people>.+)/$', views.people_detail, name='people_detail'),
#url(r'^people/add/$', views.add_people, name='add_people'),
#url(r'^people/(?P<name_people>.+)/edit/$', views.edit_people, name='edit_people'),
url(r'^autocomplete/', include('autocomplete_light.urls')),
#url(r'^accounts/login/$', 'django.contrib.auth.views.login')
)

#(?P<id_text>.+)
